### ISSUE TITLE
Add and delete buttons on option creation do not indicate that they have focus

### ISSUE THREAD

**Issue by jelhan** [jelhan/croodle#293]
The add (`+`) and delete (trash icon) used on creation of times for selected days and options do not indicate that they have focus.

**Comment by jelhan** [comment]
Both buttons are having `.btn-link` classes. Bootstrap indicates focus for `<button class="btn-link">` with an underline:

```css
.btn-link.focus,
.btn-link:focus {
    text-decoration: underline;
    border-color: transparent;
    box-shadow: none;
}
```

But that doesn't work here cause the icon has `display: inline-block`. It would work with `display: inline`:

![focus](https://user-images.githubusercontent.com/4965703/68624111-67d8df00-04d6-11ea-875c-57d302bec96b.gif)

I'm not sure if I'm convinced by that design. But it would be a quick fix for sure. @sappor0, what do you think?
